version: "3.7"

services:
  rest_api:
    image: node:18.10
    container_name: okaz_rest_api
    volumes:
      - ./:/rest_api
    working_dir: /rest_api
    entrypoint: ["/bin/sh", "-c"]
    command:
    - |
      npm i
      npm run build
      npm run start
    ports:
      - "80:3001"
    depends_on:
      - postgres

  monitoring:
    image: dpage/pgadmin4
    logging:
      driver: none
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8081:80"
    env_file:
      - ./.config/pgadmin.env
    depends_on:
      - postgres
    volumes:
      - ./pgadmin:/var/lib/pgadmin
  
  postgres:
    container_name: postgres_container
    image: postgres
    env_file:
      - ./.config/postgres.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
